"""
Metrics collection and reporting for voice agent performance.

METRIC NAME GLOSSARY (shortforms used throughout):
  
  Latency metrics (measured in seconds):
    - e2e_latency: End-to-end latency. User stops speaking → agent audio starts.
    - eou_delay: End-of-turn delay. VAD detects silence → EOU decision sent.
    - transcription_delay: Time from EOU decision → final transcript available from STT.
    - retrieval_latency: RAG retrieval time. Query embedding + Qdrant search round-trip.
    - tool_call_latency: Calendar tool latency. Full round-trip to Cal.com API.
    - llm_ttft: LLM time to first token. First completion token appears.
    - tts_ttfb: TTS time to first byte. First audio segment from synthesis engine.

  Token counts (from LLM metrics):
    - llm_prompt_tokens: Input tokens sent to LLM (includes system + context + user input).
    - llm_completion_tokens: Output tokens generated by LLM.
    - llm_cached_tokens: Prompt tokens served from cache (faster, cheaper).

  TTS metrics:
    - tts_characters: Total characters synthesized for this turn.
    - interrupted: True if TTS playback was cancelled (user barge-in or system interrupt).

  STT metrics:
    - stt_audio_secs: Duration of user audio input (seconds).

  Retrieval quality:
    - retrieval_low_confidence: True if top-k result scored below RAG_RELEVANCE_FLOOR.
    - retrieval_low_confidence_rate: Fraction of turns with low-confidence retrievals.

  Cost:
    - estimated_cost_usd: Estimated USD cost for this turn (STT + TTS + LLM tokens).

  Metadata:
    - source: "voice" for LiveKit calls, "chat" for HTTP endpoint.
    - session_id: Chat session identifier (None for voice).
    - responded: True if agent produced audio output this turn (False = barge-in or system flush).
    - tool_name: Name of calendar tool invoked ("get_available_slots", "collect_contact_info", "book_slot").

ABBREVIATIONS:
  - STT: Speech-to-Text
  - TTS: Text-to-Speech
  - LLM: Large Language Model
  - RAG: Retrieval-Augmented Generation
  - VAD: Voice Activity Detection
  - EOU: End-of-Utterance
  - TTF: Time to First (token/byte)
"""
import json
import logging
import statistics
import time
from collections import deque
from pathlib import Path
from dataclasses import asdict, dataclass
from typing import TYPE_CHECKING, Any, Optional

if TYPE_CHECKING:
    from livekit.agents.voice.agent_session import AgentSession

logger = logging.getLogger(__name__)

# kept the price tracking in usd and not inr
_INR_TO_USD: float = 1 / 95.0

# Sarvam STT (Saaras:v3): ₹30 per hour of audio
SARVAM_STT_COST_PER_SEC: float = (30.0 / 3600.0) * _INR_TO_USD  # $/sec

# Sarvam TTS (Bulbul:v3): ₹30 per 10,000 characters
SARVAM_TTS_COST_PER_CHAR: float = (30.0 / 10_000.0) * _INR_TO_USD  # $/char

# GPT-4.1-mini: $0.4/1M input tokens, $1.60/1M output tokens (USD)
GPT_INPUT_USD_PER_1M: float = 0.4  
GPT_OUTPUT_USD_PER_1M: float = 1.6
GPT_COST_PER_INPUT_TOKEN: float = GPT_INPUT_USD_PER_1M / 1_000_000
GPT_COST_PER_OUTPUT_TOKEN: float = GPT_OUTPUT_USD_PER_1M / 1_000_000

RING_BUFFER_SIZE: int = 100
METRICS_API_LIMIT: int = 100


@dataclass
class TurnMetrics:
    """Latency and cost record for one voice turn."""


    # Latency — sourced from ChatMessage.metrics (MetricsReport, pre-computed by LiveKit)
    e2e_latency: Optional[float] = None         # user stopped speaking → agent audio started
    eou_delay: Optional[float] = None           # VAD end-of-speech → EOU decision
    transcription_delay: Optional[float] = None # EOU decision → transcript ready
    retrieval_latency: Optional[float] = None   # embed + Qdrant search (in critical path)
    tool_call_latency: Optional[float] = None   # calendar tool round-trip (Cal.com); summed per turn
    llm_ttft: Optional[float] = None            # LLM time to first token
    tts_ttfb: Optional[float] = None            # TTS time to first byte (first segment only)

    retrieval_low_confidence: Optional[bool] = None  # top score below RAG_RELEVANCE_FLOOR
    tool_name: Optional[str] = None                  # last calendar tool invoked this turn

    # Token counts — from LLMMetrics (paired by recency)
    llm_prompt_tokens: int = 0
    llm_completion_tokens: int = 0
    llm_cached_tokens: int = 0

    # TTS — aggregated across all segments for this turn
    tts_characters: int = 0
    interrupted: bool = False  # True if TTS was cancelled mid-playback

    # STT audio — from STTMetrics (paired by recency)
    stt_audio_secs: float = 0.0

    # Cost estimate
    estimated_cost_usd: float = 0.0

    # Source tag — "voice" for LiveKit calls, "chat" for HTTP chat endpoint
    source: str = "voice"
    # Chat session identifier (None for voice turns)
    session_id: Optional[str] = None


@dataclass
class _InFlightTTS:
    """Accumulates TTS segments until the turn boundary fires."""
    ttfb: float           # first segment's ttfb
    total_chars: int = 0
    interrupted: bool = False


@dataclass
class _RetrievalRecord:
    """RAG retrieval result for the in-flight turn, recorded before the LLM runs."""
    latency: float
    low_confidence: bool


@dataclass
class _ToolCallRecord:
    total_latency: float
    last_name: str


class MetricsCollector:
    def __init__(self) -> None:
        self._buffer: deque[TurnMetrics] = deque(maxlen=RING_BUFFER_SIZE)

        # Queues are LIFO (pop from right) so we get the most recent match.
        self._pending_llm: deque[Any] = deque(maxlen=10)   # LLMMetrics
        self._pending_stt: deque[Any] = deque(maxlen=10)   # STTMetrics
        self._in_flight_tts: Optional[_InFlightTTS] = None # accumulates until turn seals
        self._pending_retrieval: Optional[_RetrievalRecord] = None  # set per turn before LLM
        self._pending_tool: Optional[_ToolCallRecord] = None  # set mid-turn by calendar tools

        self._total_cost_usd: float = 0.0

    # Event handlers

    def record_retrieval(self, *, latency_s: float, low_confidence: bool) -> None:
        self._pending_retrieval = _RetrievalRecord(
            latency=latency_s, low_confidence=low_confidence
        )

    def record_tool_call(self, *, name: str, latency_s: float) -> None:
        if self._pending_tool is None:
            self._pending_tool = _ToolCallRecord(total_latency=latency_s, last_name=name)
        else:
            self._pending_tool.total_latency += latency_s
            self._pending_tool.last_name = name
        logger.info(
            json.dumps({"event": "tool_call", "tool": name, "latency_s": round(latency_s, 4)})
        )

    def handle_plugin_metrics(self, metric: Any) -> None:
        from livekit.agents.metrics import LLMMetrics, STTMetrics, TTSMetrics

        if isinstance(metric, STTMetrics):
            self._pending_stt.append(metric)

        elif isinstance(metric, LLMMetrics):
            self._pending_llm.append(metric)

        elif isinstance(metric, TTSMetrics):
            # First TTS segment of a new turn initialises the in-flight tracker.
            if self._in_flight_tts is None:
                self._in_flight_tts = _InFlightTTS(ttfb=metric.ttfb)
            self._in_flight_tts.total_chars += metric.characters_count
            if metric.cancelled:
                self._in_flight_tts.interrupted = True

    def handle_conversation_item(self, event: Any) -> None:
        """Handler for "conversation_item_added" events — seals one turn."""
        from livekit.agents.llm.chat_context import ChatMessage

        item = event.item
        if not isinstance(item, ChatMessage) or item.role != "assistant":
            return

        report = item.metrics  # MetricsReport TypedDict
        self._seal(report)

    def handle_close(self, _event: Any) -> None:
        """Handler for "close" events — flushes remaining in-flight data."""
        # If the call ended mid-turn (e.g. interrupted), seal with whatever we have.
        if self._in_flight_tts is not None or self._pending_llm:
            self._seal({})

    # Internal 

    def _seal(self, report: dict) -> None:
        """Commit a TurnMetrics record from the current pending state."""
        llm = self._pending_llm.pop() if self._pending_llm else None
        stt = self._pending_stt.pop() if self._pending_stt else None
        tts = self._in_flight_tts
        self._in_flight_tts = None
        retrieval = self._pending_retrieval
        self._pending_retrieval = None
        tool = self._pending_tool
        self._pending_tool = None

        # Barge-ins and end-of-call flushes have no e2e latency; exclude them from percentiles.
        e2e_raw = report.get("e2e_latency")
        responded = bool(e2e_raw)

        if responded:
            e2e = float(e2e_raw)
            eou = _opt(report.get("end_of_turn_delay"))
            tr_delay = _opt(report.get("transcription_delay"))
            llm_ttft = _opt(report.get("llm_node_ttft")) or (_opt(llm.ttft) if llm else None)
            tts_ttfb = _opt(report.get("tts_node_ttfb")) or (_opt(tts.ttfb) if tts else None)
        else:
            e2e = eou = tr_delay = llm_ttft = tts_ttfb = None

        prompt_tok = llm.prompt_tokens if llm else 0
        completion_tok = llm.completion_tokens if llm else 0
        cached_tok = llm.prompt_cached_tokens if llm else 0

        tts_chars = tts.total_chars if tts else 0
        interrupted = tts.interrupted if tts else False
        stt_audio = stt.audio_duration if stt else 0.0

        cost = self._estimate_cost(stt_audio, tts_chars, prompt_tok, completion_tok)
        self._total_cost_usd += cost

        turn = TurnMetrics(
            timestamp=time.time(),
            responded=responded,
            e2e_latency=e2e,
            eou_delay=eou,
            transcription_delay=tr_delay,
            retrieval_latency=retrieval.latency if retrieval else None,
            tool_call_latency=tool.total_latency if tool else None,
            llm_ttft=llm_ttft,
            tts_ttfb=tts_ttfb,
            retrieval_low_confidence=retrieval.low_confidence if retrieval else None,
            tool_name=tool.last_name if tool else None,
            llm_prompt_tokens=prompt_tok,
            llm_completion_tokens=completion_tok,
            llm_cached_tokens=cached_tok,
            tts_characters=tts_chars,
            interrupted=interrupted,
            stt_audio_secs=stt_audio,
            estimated_cost_usd=round(cost, 6),
        )
        self._buffer.append(turn)
        logger.info(json.dumps({"event": "turn_metrics", **asdict(turn)}))
        persist_turn(turn)

    @staticmethod
    def _estimate_cost(
        stt_audio_secs: float,
        tts_chars: int,
        prompt_tokens: int,
        completion_tokens: int,
    ) -> float:
        return (
            stt_audio_secs * SARVAM_STT_COST_PER_SEC
            + tts_chars * SARVAM_TTS_COST_PER_CHAR
            + prompt_tokens * GPT_COST_PER_INPUT_TOKEN
            + completion_tokens * GPT_COST_PER_OUTPUT_TOKEN
        )

    # Public API

    def get_summary(self) -> dict[str, Any]:
        """Return p50/p95 stats per stage + cost totals. Fed to GET /metrics."""
        return summary_from_turns(list(self._buffer))

# Helpers

def _opt(value: Any) -> Optional[float]:
    return float(value) if value else None


def persist_turn(turn: TurnMetrics, path: str | None = None) -> None:
    if path is None:
        from utils.config import settings
        path = settings.METRICS_STORE_PATH
    try:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with open(path, "a") as f:
            f.write(json.dumps(asdict(turn)) + "\n")
    except OSError as exc:
        logger.warning("Failed to persist turn metrics to %s: %s", path, exc)


def load_turns(path: str | None = None, limit: int = METRICS_API_LIMIT) -> list[TurnMetrics]:
    if path is None:
        from utils.config import settings
        path = settings.METRICS_STORE_PATH
    try:
        with open(path) as f:
            lines = f.readlines()
    except FileNotFoundError:
        return []

    turns: list[TurnMetrics] = []
    for line in lines[-limit:]:
        line = line.strip()
        if not line:
            continue
        try:
            turns.append(TurnMetrics(**json.loads(line)))
        except (json.JSONDecodeError, TypeError) as exc:
            logger.debug("Skipping malformed metrics line: %s | error: %s", line[:120], exc)
    return turns


def summary_from_turns(turns: list[TurnMetrics]) -> dict[str, Any]:
    total_cost = sum(t.estimated_cost_usd for t in turns)
    rt = [t for t in turns if t.responded]
    base: dict[str, Any] = {
        "turn_count": len(turns),
        "response_turn_count": len(rt),
        "non_response_turn_count": len(turns) - len(rt),
        "total_cost_usd": round(total_cost, 4),
    }
    if not rt:
        return base

    def stats(vals: list[Optional[float]]) -> Optional[dict[str, float]]:
        clean = [v for v in vals if v]  # drop None and legacy 0.0 noise
        if not clean:
            return None
        # quantiles needs >= 2 points; fall back to max for a single sample.
        p95 = (
            statistics.quantiles(clean, n=100)[94] if len(clean) >= 2 else max(clean)
        )
        return {"p50": round(statistics.median(clean), 3), "p95": round(p95, 3)}

    def _source_summary(source_turns: list[TurnMetrics]) -> dict[str, Any]:
        srt = [t for t in source_turns if t.responded]
        if not srt:
            return {"turn_count": len(source_turns), "response_turn_count": 0}
        return {
            "turn_count": len(source_turns),
            "response_turn_count": len(srt),
            "e2e_latency_secs": stats([t.e2e_latency for t in srt]),
            "retrieval_latency_secs": stats([t.retrieval_latency for t in srt]),
            "llm_ttft_secs": stats([t.llm_ttft for t in srt]),
            "retrieval_low_confidence_rate": round(
                sum(1 for t in srt if t.retrieval_low_confidence) / len(srt), 3
            ),
        }

    voice_turns = [t for t in turns if getattr(t, "source", "voice") == "voice"]
    chat_turns = [t for t in turns if getattr(t, "source", "voice") == "chat"]

    return base | {
        "e2e_latency_secs": stats([t.e2e_latency for t in rt]),
        "retrieval_latency_secs": stats([t.retrieval_latency for t in rt]),
        "tool_call_latency_secs": stats([t.tool_call_latency for t in rt]),
        "llm_ttft_secs": stats([t.llm_ttft for t in rt]),
        "tts_ttfb_secs": stats([t.tts_ttfb for t in rt]),
        "transcription_delay_secs": stats([t.transcription_delay for t in rt]),
        "eou_delay_secs": stats([t.eou_delay for t in rt]),
        "interruption_rate": round(
            sum(1 for t in rt if t.interrupted) / len(rt), 3
        ),
        "retrieval_low_confidence_rate": round(
            sum(1 for t in rt if t.retrieval_low_confidence) / len(rt), 3
        ),
        "avg_tokens": {
            "prompt": round(statistics.mean(t.llm_prompt_tokens for t in rt), 1),
            "completion": round(statistics.mean(t.llm_completion_tokens for t in rt), 1),
            "cached": round(statistics.mean(t.llm_cached_tokens for t in rt), 1),
        },
        "by_source": {
            "voice": _source_summary(voice_turns),
            "chat": _source_summary(chat_turns),
        },
        "recent_turns": [asdict(t) for t in turns[-10:]],
    }


def attach_metrics(
    session: "AgentSession",
    collector: MetricsCollector,
    *,
    stt: Any,
    llm: Any,
    tts: Any,
) -> None:
    stt.on("metrics_collected", collector.handle_plugin_metrics)
    llm.on("metrics_collected", collector.handle_plugin_metrics)
    tts.on("metrics_collected", collector.handle_plugin_metrics)

    session.on("conversation_item_added", collector.handle_conversation_item)
    session.on("close", collector.handle_close)
